apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: boxz2cbvb-dotnet-basic
  janus-idp.io/tekton: boxz2cbvb-dotnet-basic
  backstage.io/kubernetes-id: boxz2cbvb-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: boxz2cbvb-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
